### ISSUE TITLE
Update section on recipe

### ISSUE THREAD

**Issue by icaoberg** [pscedu/singularity-bwa#1]
Update section to reflect this belongs to PSC

https://github.com/pscedu/singularity-bwa/blob/2cfd79f81b0d2e831db4bf1cfcea8a6831843594/0.7.3a/Singularity#L4

**Comment by halbakri** [comment]
The section is updated with the following: 
%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://gitub.com/pscedu/singularity-bwa
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 0.7.3a

Should I change email and author??
